apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: joaopgs4/gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80  # Changed from 8080 to 80
        env:
        - name: LOGGING_LEVEL_STORE
          value: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80           # Service port exposed (default HTTP port)
    targetPort: 80     # Port on the container
  type: LoadBalancer
